extensions:
- name: seq
  logPath: ./.logs

services:
- name: frontend
  project: src/Weather.Frontend/Weather.Frontend.csproj
- name: backend
  project: src/Weather.Backend/Weather.Backend.csproj
- name: redis
  image: redis
  bindings:
  - port: 6379
    connectionString: "${host}:${port}"
- name: redis-cli
  image: redis
  args: "redis-cli -h redis MONITOR"
